.TH C-PRINTF 1 man_3_printf\-0.1
.SH NAME
C-PRINTF - It prints formatted output.
.SH LIBRARY
Standard C library
.SH SYNOPSIS
.BR C-PRINTF
.BR #include 
.RB < \-main.h
.R >
.P
.BR int _printf(const char *format, ...);
.SH DESCRIPTION
.B C-PRINTF
is a program that prints formatted output for C-PRINTF project
.SH RETURN VALUE
The
.B C-PRINTF
.I function
.R returns the number of characters printed (excluding the null)
.SH EXAMPLE
.I int
main() {
.P
n = 10;
.P
_printf("The value of n is: %d\n", n);
.P
return (0);
.P
}
.SH AUTHOR(S)
This code was mostly written in collaboration by
.I Kryss Babilonia
.B &
.I Angel Velazquez
.R for a project called C-printf
.SH Bugs
If encountering any issues, I recommend making your own program instead.Do some research. Do some more research. Maybe ask some peers. Or call Kryss.
.SH COPYRIGHT
Copyright \(co 2024 [
.I HOLBERTON C SCHOOL
.R ]
.SH NOTES
.B  This man page was completed for proper documentation of a function.
